
-- create table user (id bigint generated by default as identity, username varchar(255), age int, primary key (id));
drop TABLE  IF EXISTS `user`;
CREATE TABLE `user` (
	`id` int NOT NULL,
	`username` varchar(255),
	`age` int(2),
	PRIMARY KEY (`id`)
) COMMENT='';